/**
 * registerSW.js — Service Worker Registration
 * ─────────────────────────────────────────────
 * This file registers the service worker that was auto-generated by
 * vite-plugin-pwa (Workbox) during the production build.
 *
 * What it does:
 * 1. Registers the SW with the browser via navigator.serviceWorker.register()
 * 2. Handles the "new version available" event → prompts user to reload
 * 3. Handles the "offline ready" event → logs confirmation
 * 4. Periodically checks for SW updates (every hour)
 *
 * This file is imported in main.jsx and runs once when the app loads.
 * In development mode, the SW is not active (only works in production builds).
 */

import { registerSW } from "virtual:pwa-register";

const updateSW = registerSW({
  /**
   * Called when a new service worker is available and waiting to activate.
   * This happens when you deploy a new version of the app.
   * We prompt the user to reload so they get the latest version.
   */
  onNeedRefresh() {
    if (confirm("A new version of TaskBnb is available. Reload to update?")) {
      updateSW(true); // skipWaiting + reload
    }
  },

  /**
   * Called when all app assets have been precached and the app
   * can now work fully offline. This fires on the very first visit
   * after the SW finishes installing.
   */
  onOfflineReady() {
    console.log("[PWA] TaskBnb is ready to work offline.");
  },

  /**
   * Called after the service worker has been successfully registered.
   * We use this to set up a periodic update check (every 1 hour).
   * This ensures users get new versions even if they keep the tab open
   * for extended periods.
   *
   * @param {string} swUrl - The URL of the registered service worker
   * @param {ServiceWorkerRegistration} registration - The SW registration object
   */
  onRegisteredSW(swUrl, registration) {
    if (registration) {
      setInterval(
        () => {
          registration.update();
        },
        60 * 60 * 1000 // Check every 1 hour
      );
    }
  },

  /**
   * Called if service worker registration fails.
   * Common causes: browser doesn't support SW, or HTTPS is not available.
   */
  onRegisterError(error) {
    console.error("[PWA] Service worker registration failed:", error);
  },
});
