const clientData = [
    {
        id: 1,
        name: "John Doe",
        avatar: "J",
        email: "john.doe@example.com",
        phone: "+1 234 567 8900",
        company: "TechCorp Inc.",
        registrationDate: "2024-03-15",
        plan: "Basic",
        status: "Active",
        validityDate: "2025-03-15",
    },
    {
        id: 2,
        name: "Sarah Wilson",
        avatar: "S",
        email: "sarah.wilson@example.com",
        phone: "+1 234 567 8901",
        company: "Digital Solutions Ltd.",
        registrationDate: "2024-02-20",
        plan: "Premium",
        status: "Active",
        validityDate: "2025-02-20",
    },
    {
        id: 3,
        name: "Michael Chen",
        avatar: "M",
        email: "michael.chen@example.com",
        phone: "+1 234 567 8902",
        company: "Innovation Hub",
        registrationDate: "2024-01-10",
        plan: "Enterprise",
        status: "Active",
        validityDate: "2025-01-10",
    },
    {
        id: 4,
        name: "Emma Davis",
        avatar: "E",
        email: "emma.davis@example.com",
        phone: "+1 234 567 8903",
        company: "Creative Agency",
        registrationDate: "2024-04-05",
        plan: "Basic",
        status: "Inactive",
        validityDate: "2025-04-05",
    },
    {
        id: 5,
        name: "David Martinez",
        avatar: "D",
        email: "david.martinez@example.com",
        phone: "+1 234 567 8904",
        company: "Global Ventures",
        registrationDate: "2024-03-22",
        plan: "Premium",
        status: "Active",
        validityDate: "2025-03-22",
    },
    {
        id: 6,
        name: "Lisa Anderson",
        avatar: "L",
        email: "lisa.anderson@example.com",
        phone: "+1 234 567 8905",
        company: "Marketing Pro",
        registrationDate: "2024-02-14",
        plan: "Basic",
        status: "Active",
        validityDate: "2025-02-14",
    },
    {
        id: 7,
        name: "Robert Taylor",
        avatar: "R",
        email: "robert.taylor@example.com",
        phone: "+1 234 567 8906",
        company: "Tech Innovations",
        registrationDate: "2024-01-28",
        plan: "Enterprise",
        status: "Active",
        validityDate: "2025-01-28",
    },
    {
        id: 8,
        name: "Jennifer Lee",
        avatar: "J",
        email: "jennifer.lee@example.com",
        phone: "+1 234 567 8907",
        company: "Design Studio",
        registrationDate: "2024-03-08",
        plan: "Premium",
        status: "Pending",
        validityDate: "2025-03-08",
    },
    {
        id: 9,
        name: "James Brown",
        avatar: "J",
        email: "james.brown@example.com",
        phone: "+1 234 567 8908",
        company: "Finance Group",
        registrationDate: "2024-04-12",
        plan: "Basic",
        status: "Active",
        validityDate: "2025-04-12",
    },
    {
        id: 10,
        name: "Patricia Moore",
        avatar: "P",
        email: "patricia.moore@example.com",
        phone: "+1 234 567 8909",
        company: "Consulting Partners",
        registrationDate: "2024-02-05",
        plan: "Premium",
        status: "Active",
        validityDate: "2025-02-05",
    },
    {
        id: 11,
        name: "Christopher White",
        avatar: "C",
        email: "christopher.white@example.com",
        phone: "+1 234 567 8910",
        company: "Software Systems",
        registrationDate: "2024-01-18",
        plan: "Enterprise",
        status: "Inactive",
        validityDate: "2025-01-18",
    },
    {
        id: 12,
        name: "Amanda Harris",
        avatar: "A",
        email: "amanda.harris@example.com",
        phone: "+1 234 567 8911",
        company: "Media Networks",
        registrationDate: "2024-03-30",
        plan: "Basic",
        status: "Active",
        validityDate: "2025-03-30",
    },
    {
        id: 13,
        name: "Daniel Clark",
        avatar: "D",
        email: "daniel.clark@example.com",
        phone: "+1 234 567 8912",
        company: "Cloud Services Inc.",
        registrationDate: "2024-02-25",
        plan: "Premium",
        status: "Active",
        validityDate: "2025-02-25",
    },
    {
        id: 14,
        name: "Michelle Lewis",
        avatar: "M",
        email: "michelle.lewis@example.com",
        phone: "+1 234 567 8913",
        company: "Data Analytics Co.",
        registrationDate: "2024-04-01",
        plan: "Enterprise",
        status: "Active",
        validityDate: "2025-04-01",
    },
    {
        id: 15,
        name: "Kevin Walker",
        avatar: "K",
        email: "kevin.walker@example.com",
        phone: "+1 234 567 8914",
        company: "Security Solutions",
        registrationDate: "2024-01-12",
        plan: "Basic",
        status: "Pending",
        validityDate: "2025-01-12",
    },
    {
        id: 16,
        name: "Nancy Hall",
        avatar: "N",
        email: "nancy.hall@example.com",
        phone: "+1 234 567 8915",
        company: "Healthcare Systems",
        registrationDate: "2024-03-18",
        plan: "Premium",
        status: "Active",
        validityDate: "2025-03-18",
    },
    {
        id: 17,
        name: "Brian Allen",
        avatar: "B",
        email: "brian.allen@example.com",
        phone: "+1 234 567 8916",
        company: "Education Tech",
        registrationDate: "2024-02-08",
        plan: "Basic",
        status: "Active",
        validityDate: "2025-02-08",
    },
    {
        id: 18,
        name: "Karen Young",
        avatar: "K",
        email: "karen.young@example.com",
        phone: "+1 234 567 8917",
        company: "E-commerce Plus",
        registrationDate: "2024-04-20",
        plan: "Enterprise",
        status: "Active",
        validityDate: "2025-04-20",
    },
    {
        id: 19,
        name: "Steven King",
        avatar: "S",
        email: "steven.king@example.com",
        phone: "+1 234 567 8918",
        company: "Logistics Pro",
        registrationDate: "2024-01-25",
        plan: "Premium",
        status: "Inactive",
        validityDate: "2025-01-25",
    },
    {
        id: 20,
        name: "Betty Wright",
        avatar: "B",
        email: "betty.wright@example.com",
        phone: "+1 234 567 8919",
        company: "Retail Dynamics",
        registrationDate: "2024-03-12",
        plan: "Basic",
        status: "Active",
        validityDate: "2025-03-12",
    },
];

export default clientData;